close all;
clear;
clc;  

%% HK参数设置
%Hankel矩阵阶次
k = 10;
%系统阶次
m = 2;
%采样时间
Ts = 1/1000;
s=tf('s');

opts = bodeoptions;
opts.FreqUnits = 'Hz';       
opts.PhaseWrapping = 'on';
opts.XLim = [1, 1/(2*Ts)];

Rs_O = 5.70125;
Ld_O = 1.86152e-3;
Psi_O = 9.65548e-3;
Lq_O = 2.16828e-3;
p = 14;

%% 测量
data = readmatrix("Speed_2.txt", 'NumHeaderLines', 1);
fprintf('工作点2V：\n');
Uq = data(end-2046:end,9) - 2;
Id = data(end-2046:end,5);
Iq = data(end-2046:end,6);
n = data(end-2046:end,3);
DCGAIN(1) = mean(n)/2;
n = n - mean(n);
we = n / 60 * 2 * pi * p;
% Uq = Uq - we.*Psi_O;
Teqd = 1.5*p.*Iq.*((Ld_O-Lq_O).*Id+Psi_O);
Teq = 1.5*p*Psi_O.*Iq;
Eqd = we.*(Psi_O+Ld_O.*Id);
Eq = we.*Psi_O;
[sys_tf_p2,~] = DataProcess(Uq,n,k,m,Ts);
sys_tf_p2 = sys_tf_p2 * DCGAIN(1) / dcgain(sys_tf_p2);
figure(Name='理想假设分析');
subplot(1,2,1);
plot(Teq);
hold on;
plot(Teqd);
legend('id=0电磁转矩','id≠0电磁转矩');
subplot(1,2,2);
plot(Eq);
hold on;
plot(Eqd);
legend('id=0反电动势','id≠0反电动势');
fprintf('电磁转矩理想化分析：\n');
Signal_Analyse(Teq,Teqd);
fprintf('反电动势分析：\n');
Signal_Analyse(Eq,Eqd);
figure(Name='相干函数对比');
[gamma_Uq, F] = mscohere(Uq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Uq = 20*log10(gamma_Uq);
[gamma_Iq, ~] = mscohere(Iq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Iq = 20*log10(gamma_Iq);
semilogx(F,gamma_Uq,F,gamma_Iq);
grid on;
grid minor;
xlabel('频率/Hz');
ylabel('分贝/dB');
subtitle('输入输出相干函数');
legend('Uq->n','Iq->n');
ylim([-0.5,0]);
xlim([1,300]);

data = readmatrix("Speed_4.txt", 'NumHeaderLines', 1);
fprintf('\n工作点4V：\n');
Uq = data(end-2046:end,9) - 4;
Id = data(end-2046:end,5);
Iq = data(end-2046:end,6);
n = data(end-2046:end,3);
DCGAIN(2) = mean(n)/4;
n = n - mean(n);
we = n / 60 * 2 * pi * p;
% Uq = Uq - we.*Psi_O;
Teqd = 1.5*p.*Iq.*((Ld_O-Lq_O).*Id+Psi_O);
Teq = 1.5*p*Psi_O.*Iq;
Eqd = we.*(Psi_O+Ld_O.*Id);
Eq = we.*Psi_O;
[sys_tf_p4,~] = DataProcess(Uq,n,k,m,Ts);
sys_tf_p4 = sys_tf_p4 * DCGAIN(2) / dcgain(sys_tf_p4);
figure(Name='理想假设分析');
subplot(1,2,1);
plot(Teq);
hold on;
plot(Teqd);
legend('id=0电磁转矩','id≠0电磁转矩');
subplot(1,2,2);
plot(Eq);
hold on;
plot(Eqd);
legend('id=0反电动势','id≠0反电动势');
fprintf('电磁转矩理想化分析：\n');
Signal_Analyse(Teq,Teqd);
fprintf('反电动势分析：\n');
Signal_Analyse(Eq,Eqd);
figure(Name='相干函数对比');
[gamma_Uq, F] = mscohere(Uq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Uq = 20*log10(gamma_Uq);
[gamma_Iq, ~] = mscohere(Iq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Iq = 20*log10(gamma_Iq);
semilogx(F,gamma_Uq,F,gamma_Iq);
grid on;
grid minor;
xlabel('频率/Hz');
ylabel('分贝/dB');
subtitle('输入输出相干函数');
legend('Uq->n','Iq->n');
ylim([-0.5,0]);
xlim([1,300]);

data = readmatrix("Speed_-2.txt", 'NumHeaderLines', 1);
fprintf('\n工作点-2V：\n');
Uq = data(end-2046:end,9)+2;
Id = data(end-2046:end,5);
Iq = data(end-2046:end,6);
n = data(end-2046:end,3);
DCGAIN(3) = mean(n)/-2;
n = n - mean(n);
we = n / 60 * 2 * pi * p;
% Uq = Uq - we.*Psi_O;
Teqd = 1.5*p.*Iq.*((Ld_O-Lq_O).*Id+Psi_O);
Teq = 1.5*p*Psi_O.*Iq;
Eqd = we.*(Psi_O+Ld_O.*Id);
Eq = we.*Psi_O;
[sys_tf_n2,~] = DataProcess(Uq,n,k,m,Ts);
sys_tf_n2 = sys_tf_n2 * DCGAIN(3) / dcgain(sys_tf_n2);
figure(Name='理想假设分析');
subplot(1,2,1);
plot(Teq);
hold on;
plot(Teqd);
legend('id=0电磁转矩','id≠0电磁转矩');
subplot(1,2,2);
plot(Eq);
hold on;
plot(Eqd);
legend('id=0反电动势','id≠0反电动势');
fprintf('电磁转矩理想化分析：\n');
Signal_Analyse(Teq,Teqd);
fprintf('反电动势分析：\n');
Signal_Analyse(Eq,Eqd);
figure(Name='相干函数对比');
[gamma_Uq, F] = mscohere(Uq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Uq = 20*log10(gamma_Uq);
[gamma_Iq, ~] = mscohere(Iq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Iq = 20*log10(gamma_Iq);
semilogx(F,gamma_Uq,F,gamma_Iq);
grid on;
grid minor;
xlabel('频率/Hz');
ylabel('分贝/dB');
subtitle('输入输出相干函数');
legend('Uq->n','Iq->n');
ylim([-0.5,0]);
xlim([1,300]);

data = readmatrix("Speed_-4.txt", 'NumHeaderLines', 1);
fprintf('\n工作点-4V：\n');
Uq = data(end-2046:end,9)+4;
Id = data(end-2046:end,5);
Iq = data(end-2046:end,6);
n = data(end-2046:end,3);
DCGAIN(4) = mean(n)/-4;
n = n - mean(n);
we = n / 60 * 2 * pi * p;
% Uq = Uq - we.*Psi_O;
Teqd = 1.5*p.*Iq.*((Ld_O-Lq_O).*Id+Psi_O);
Teq = 1.5*p*Psi_O.*Iq;
Eqd = we.*(Psi_O+Ld_O.*Id);
Eq = we.*Psi_O;
[sys_tf_n4,~] = DataProcess(Uq,n,k,m,Ts);
sys_tf_n4 = sys_tf_n4 * DCGAIN(4) / dcgain(sys_tf_n4);
figure(Name='理想假设分析');
subplot(1,2,1);
plot(Teq);
hold on;
plot(Teqd);
legend('id=0电磁转矩','id≠0电磁转矩');
subplot(1,2,2);
plot(Eq);
hold on;
plot(Eqd);
legend('id=0反电动势','id≠0反电动势');
fprintf('电磁转矩理想化分析：\n');
Signal_Analyse(Teq,Teqd);
fprintf('反电动势分析：\n');
Signal_Analyse(Eq,Eqd);
figure(Name='相干函数对比');
[gamma_Uq, F] = mscohere(Uq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Uq = 20*log10(gamma_Uq);
[gamma_Iq, ~] = mscohere(Iq,n, hamming(256), 16, 2048, 1/Ts);
gamma_Iq = 20*log10(gamma_Iq);
semilogx(F,gamma_Uq,F,gamma_Iq);
grid on;
grid minor;
xlabel('频率/Hz');
ylabel('分贝/dB');
subtitle('输入输出相干函数');
legend('Uq->n','Iq->n');
ylim([-0.5,0]);
xlim([1,300]);

%% 多工作点辨识结果分析
figure(Name='多工作点分析');
subplot(1,2,1);
subtitle('频率特性');
bode(sys_tf_p2,sys_tf_p4,sys_tf_n2,sys_tf_n4,opts);
grid on;
grid minor;
legend('2V','4V','-2V','-4V');
subplot(1,2,2);
subtitle('零极点图');
pzmap(sys_tf_p2,sys_tf_p4,sys_tf_n2,sys_tf_n4);
grid on;
grid minor;
legend('2V','4V','-2V','-4V');

%% 利用闭环传递函数反求解机械传递函数
K = 1.5 * p * Psi_O;
Kf = pi / 30 * p * Psi_O;
G_RL = 1/(Rs_O+Lq_O*s);

hat_H_p2 = d2c(sys_tf_p2,'zoh');
hat_G_p2 = hat_H_p2/G_RL/(K - K * Kf * hat_H_p2);
hat_C_p2 = feedback(hat_G_p2*G_RL*K,Kf);
DC(1) = dcgain(hat_G_p2);
Pole(1,:) = pole(hat_G_p2);
Zero(1,:) = zero(hat_G_p2);

hat_H_p4 = d2c(sys_tf_p4,'zoh');
hat_G_p4 = hat_H_p4/G_RL/(K - K * Kf * hat_H_p4);
hat_C_p4 = feedback(hat_G_p4*G_RL*K,Kf);
DC(2) = dcgain(hat_G_p4);
Pole(2,:) = pole(hat_G_p4);
Zero(2,:) = zero(hat_G_p4);

hat_H_n2 = d2c(sys_tf_n2,'zoh');
hat_G_n2 = hat_H_n2/G_RL/(K - K * Kf * hat_H_n2);
hat_C_n2 = feedback(hat_G_n2*G_RL*K,Kf);
DC(3) = dcgain(hat_G_n2);
Pole(3,:) = pole(hat_G_n2);
Zero(3,:) = zero(hat_G_n2);

hat_H_n4 = d2c(sys_tf_n4,'zoh');
hat_G_n4 = hat_H_n4/G_RL/(K - K * Kf * hat_H_n4);
hat_C_n4 = feedback(hat_G_n4*G_RL*K,Kf);
DC(4) = dcgain(hat_G_n4);
Pole(4,:) = pole(hat_G_n4);
Zero(4,:) = zero(hat_G_n4);

figure(Name='反求机械模态分析');
subplot(1,2,1);
bode(hat_G_p2,hat_G_p4,hat_G_n2,hat_G_n4,opts);
grid on;
grid minor;
legend('2V','4V','-2V','-4V');
subplot(1,2,2);
pzmap(hat_G_p2,hat_G_p4,hat_G_n2,hat_G_n4);
grid on;
grid minor;
legend('2V','4V','-2V','-4V');
figure(Name='反求机械模态重构闭环分析');
subplot(1,2,1);
bode(hat_H_p2,hat_H_p4,hat_H_n2,hat_H_n4,hat_C_p2,hat_C_p4,hat_C_n2,hat_C_n4,opts);
grid on;
grid minor;
legend('2V','4V','-2V','-4V','2V（重构）','4V（重构）','-2V（重构）','-4V（重构）');
subplot(1,2,2);
pzmap(hat_H_p2,hat_H_p4,hat_H_n2,hat_H_n4,hat_C_p2,hat_C_p4,hat_C_n2,hat_C_n4);
grid on;
grid minor;
legend('2V','4V','-2V','-4V','2V（重构）','4V（重构）','-2V（重构）','-4V（重构）');
figure(Name='反求机械模态阶跃响应');
step(hat_G_p2,hat_G_p4,hat_G_n2,hat_G_n4);
grid on;
grid minor;
legend('2V','4V','-2V','-4V');
fprintf(['闭环增益：' ...
    '\n%.5f     %.5f    %.5f    %.5f\n'], ...
    DCGAIN(1), DCGAIN(2), DCGAIN(3), DCGAIN(4));
fprintf('平均直流增益：%.5f\n',mean(DC));
fprintf(['平均极点：' ...
    '\n%.5f     %.5f    %.5f    %.5f\n'], ...
    mean(Pole(:,1)), mean(Pole(:,2)), mean(Pole(:,3)), mean(Pole(:,4)));
fprintf(['平均零点：' ...
    '\n%.5f     %.5f    %.5f    %.5f\n'], ...
    mean(Zero(:,1)), mean(Zero(:,2)), mean(Zero(:,3)), mean(Zero(:,4)));